name: publish
on:
  - push
jobs:
  publish-ci-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the CI Docker image
        run: |
          [ ${GITHUB_REF#refs/heads/} == "master" ] && export IMAGE_TAG=latest || IMAGE_TAG=${GITHUB_REF#refs/heads/}
          docker build . --tag ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}
          docker run ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}
          docker push ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}
